[workspace]
members = ["test", "server", "client", "common"]
# default-members = ["quinn", "quinn-proto", "quinn-udp", "bench", "perf"]
resolver = "2"
# [profile.bench]
# debug = true

# [profile.release]
# debug = true
# 122.51.128.39
